spring:
  profiles:
    active: stage

queue:
  portfolioQueues:
    PE: https://sqs.us-east-1.amazonaws.com/492302560554/pe-portfolio,
    CO: https://sqs.us-east-1.amazonaws.com/492302560554/co-portfolio
  balanceQueues:
    PE: https://sqs.us-east-1.amazonaws.com/492302560554/pe-balance,
    CO: https://sqs.us-east-1.amazonaws.com/492302560554/co-balance